[theme]
primaryColor = "#0a3323"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f7f4d5"
textColor = "#000000"
secindaryTextColor = "#839958"
font = "sans serif"

[server]
headless = true
port = 8501
address = "0.0.0.0"
enableCORS = false
enableXsrfProtection = false
fileWatcherType = "none"
